# Makefile for the Linux video drivers on sunxi platform.
# 16 Aug 2014, Tyle, <mailto:tyle@allwinnertech.com>
# Rewritten to use lists instead of if-statements.

obj-$(CONFIG_SUNIV_FB)     += disp/
obj-$(CONFIG_SUNIV_LCD)    += lcd/
obj-$(CONFIG_SUNIV_HDMI)   += hdmi/